server:
  port: 8080

spring:
  profiles:
    include: local

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  devtools:
    remote:
      restart:
        enabled: true

logging:
  level:
    com.zaxxer.hikari: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: OFF
    p6spy: DEBUG
