spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/officezip
    driver-class-name: org.postgresql.Driver
    username: devuser
    password: devpass

  data:
    redis:
      port: 6379
      host: localhost
      password: redis@local

  jpa:
    database: postgresql
    defer-datasource-initialization: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        transaction:
          jta:
            platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
