INSERT INTO tbl_otz_organization(id,
                                 created_at,
                                 deleted_at,
                                 updated_at,
                                 "domain",
                                 organization_name)
VALUES ('e962b2d0-04a9-4a1d-8518-e7b40748aa64'::uuid,
        '2025-07-30 14:24:03.831998',
        NULL,
        '2025-07-30 14:24:03.831998',
        'admin.com',
        '관리자');

INSERT INTO public.tbl_otz_user (join_year,
                                 login_fail_count,
                                 marketing_agree,
                                 privacy_agree,
                                 terms_agree,
                                 created_at,
                                 deleted_at,
                                 last_failed_login_at,
                                 last_login_at,
                                 password_updated_at,
                                 updated_at,
                                 id,
                                 job,
                                 "position",
                                 email,
                                 nickname,
                                 last_login_ip,
                                 password_hash,
                                 profile_image_url,
                                 "role",
                                 status,
                                 organization_id)
VALUES ('2025',
        0,
        true,
        true,
        true,
        '2025-07-30 14:24:03.831998',
        NULL,
        NULL,
        '2025-08-05 16:36:10.163061',
        '2025-08-04 10:47:48.471525',
        '2025-08-01 13:57:41.409718', '43779923-2bbf-47f8-a73b-2fa79d7e13e8'::uuid,
        'DEVELOPMENT',
        'SENIOR',
        'admin@admin.com',
        '관리자',
        NULL,
        '$2a$10$3vQGmJtNjUdfm4gVJjqjBO/.SEZPUN8PqxojtYkZiTUDXnLPZQl2m',
        NULL,
        'ROLE_ADMIN',
        'ACTIVE',
        'e962b2d0-04a9-4a1d-8518-e7b40748aa64'::uuid);
